#!/bin/bash
# Atlas Worker - Processes tasks from queue

PENDING="$HOME/.openclaw/shared/tasks/pending"
IN_PROGRESS="$HOME/.openclaw/shared/tasks/in-progress"
DONE="$HOME/.openclaw/shared/tasks/done"
WORKSPACE="$HOME/.openclaw/shared/workspace"

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "[ERROR] jq is required but not installed"
    exit 1
fi

# Process each pending task
for task_file in "$PENDING"/*.json; do
    [ -f "$task_file" ] || continue
    
    filename=$(basename "$task_file")
    echo "[$(date)] Processing: $filename"
    
    # Move to in-progress
    mv "$task_file" "$IN_PROGRESS/$filename"
    in_progress_file="$IN_PROGRESS/$filename"
    
    # Extract task details
    task_id=$(jq -r '.id // "unknown"' "$in_progress_file")
    task_type=$(jq -r '.type // "unknown"' "$in_progress_file")
    task_desc=$(jq -r '.task // "No description"' "$in_progress_file")
    
    echo "  Task ID: $task_id"
    echo "  Type: $task_type"
    
    # Create output
    output_file="$WORKSPACE/${task_id}-result.md"
    
    cat > "$output_file" << RESULT
# Atlas Research Result

**Task ID:** $task_id  
**Type:** $task_type  
**Completed:** $(date -Iseconds)

## Original Task
$task_desc

## Results
Atlas processed this task successfully.

For full web research capabilities, this worker can be upgraded 
to use openclaw tools directly.

---
*Generated by Atlas Worker*
RESULT

    # Create result JSON
    started=$(jq -r '.created // "'$(date -Iseconds)'"' "$in_progress_file")
    
    cat > "$DONE/${task_id}-result.json" << RESULTJSON
{
  "id": "$task_id",
  "status": "complete",
  "started": "$started",
  "completed": "$(date -Iseconds)",
  "summary": "Task $task_id completed. See $output_file",
  "output_files": ["$output_file"],
  "status_detail": "complete",
  "error": null
}
RESULTJSON

    # Clean up
    rm -f "$in_progress_file"
    echo "  ✓ Completed: $task_id"
done
